from __future__ import annotations

from copy import deepcopy


TASK_SPECS = [
    {
        "id": "paper_extract",
        "label": "论文抽取",
        "description": "读取 PDF，抽取结构化结果",
        "category": "论文",
        "task_type": "vlm",
        "legacy_field": "vlm_model",
        "recommended_model_id": "openai/gpt-4o",
    },
    {
        "id": "paper_chat",
        "label": "论文追问",
        "description": "在单篇论文上下文内追问",
        "category": "论文",
        "task_type": "vlm",
        "legacy_field": "vlm_model",
        "recommended_model_id": "openai/gpt-4o",
    },
    {
        "id": "embedding",
        "label": "图谱向量与相似边",
        "description": "节点向量化与 similar 相似连接",
        "category": "图谱",
        "task_type": "embedding",
        "legacy_field": "embedding_model",
        "recommended_model_id": "openai/text-embedding-3-small",
    },
    {
        "id": "wiki_compile",
        "label": "Wiki 编译",
        "description": "论文页、概念页和 index.md 的文本编译",
        "category": "知识库",
        "task_type": "llm",
        "legacy_field": "wiki_compile_model",
        "recommended_model_id": "openai/gpt-4o-mini",
    },
    {
        "id": "ask_agent",
        "label": "Ask 页面",
        "description": "跨 wiki 的工具调用式问答",
        "category": "知识库",
        "task_type": "llm",
        "legacy_field": "wiki_compile_model",
        "recommended_model_id": "openai/gpt-4o-mini",
    },
    {
        "id": "ask_synthesis",
        "label": "Ask 生成概念",
        "description": "Ask 回答沉淀为概念页前的整理、判重与关系生成",
        "category": "知识库",
        "task_type": "llm",
        "legacy_field": "wiki_compile_model",
        "recommended_model_id": "openai/gpt-4o-mini",
    },
    {
        "id": "promotion_judge",
        "label": "概念精选 / 晋升判断",
        "description": "对候选概念做 promote / reject 判断",
        "category": "知识库",
        "task_type": "llm",
        "legacy_field": "wiki_compile_model",
        "recommended_model_id": "openai/gpt-4o-mini",
    },
    {
        "id": "wiki_lint",
        "label": "Wiki 健康检查",
        "description": "扫描存量 wiki：短桩 / 可合并 / 缺横切概念 / 追问建议",
        "category": "知识库",
        "task_type": "llm",
        "legacy_field": "wiki_compile_model",
        "recommended_model_id": "openai/gpt-4o-mini",
    },
]


TASK_BINDING_DEFAULTS = {
    "paper_extract": "openai/gpt-4o",
    "paper_chat": "openai/gpt-4o",
    "embedding": "openai/text-embedding-3-small",
    "wiki_compile": "openai/gpt-4o-mini",
    "ask_agent": "openai/gpt-4o-mini",
    "ask_synthesis": "openai/gpt-4o-mini",
    "promotion_judge": "openai/gpt-4o-mini",
    "wiki_lint": "openai/gpt-4o-mini",
}


AVAILABLE_PROVIDER_TYPES = [
    {"id": "openai", "label": "OpenAI 原生"},
    {"id": "openai_compatible", "label": "OpenAI 兼容 API"},
    {"id": "codex_cli", "label": "本机 Codex CLI"},
]


DEFAULT_PROVIDER_REGISTRY = [
    {
        "id": "openai",
        "label": "OpenAI",
        "provider_type": "openai",
        "base_url": "https://api.openai.com/v1",
        "api_key": "",
        "healthcheck_model": "gpt-4o-mini",
        "enabled": True,
        "last_tested_at": None,
        "last_test_status": "never",
        "last_test_message": "",
    },
    {
        "id": "kimi",
        "label": "Kimi",
        "provider_type": "openai_compatible",
        "base_url": "https://api.moonshot.cn/v1",
        "api_key": "",
        "healthcheck_model": "kimi-k2.5",
        "enabled": False,
        "last_tested_at": None,
        "last_test_status": "never",
        "last_test_message": "",
    },
    {
        "id": "deepseek",
        "label": "DeepSeek",
        "provider_type": "openai_compatible",
        "base_url": "https://api.deepseek.com",
        "api_key": "",
        "healthcheck_model": "deepseek-v4-flash",
        "enabled": False,
        "last_tested_at": None,
        "last_test_status": "never",
        "last_test_message": "",
    },
    {
        "id": "qwen",
        "label": "Qwen",
        "provider_type": "openai_compatible",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_key": "",
        "healthcheck_model": "qwen-plus",
        "enabled": False,
        "last_tested_at": None,
        "last_test_status": "never",
        "last_test_message": "",
    },
    {
        "id": "minimax",
        "label": "MiniMax",
        "provider_type": "openai_compatible",
        "base_url": "https://api.minimax.io/v1",
        "api_key": "",
        "healthcheck_model": "MiniMax-M2.7",
        "enabled": False,
        "last_tested_at": None,
        "last_test_status": "never",
        "last_test_message": "",
    },
    {
        "id": "codex-cli",
        "label": "Codex CLI",
        "provider_type": "codex_cli",
        "command": "codex",
        "healthcheck_model": "gpt-5.4-mini",
        "enabled": False,
        "last_tested_at": None,
        "last_test_status": "never",
        "last_test_message": "",
    },
]


_OPENAI_CHAT_TASKS = [
    "paper_extract",
    "paper_chat",
    "wiki_compile",
    "ask_agent",
    "ask_synthesis",
    "promotion_judge",
    "wiki_lint",
]

_OPENAI_TEXT_TASKS = [
    "wiki_compile",
    "ask_synthesis",
    "promotion_judge",
    "wiki_lint",
]

_CODEX_ALL_NON_EMBED_TASKS = [
    "paper_extract",
    "paper_chat",
    "wiki_compile",
    "ask_agent",
    "ask_synthesis",
    "promotion_judge",
    "wiki_lint",
]

_OPENAPI_LLM_TASKS = [
    "wiki_compile",
    "ask_agent",
    "ask_synthesis",
    "promotion_judge",
    "wiki_lint",
]


BUILTIN_MODEL_REGISTRY = [
    {
        "id": "openai/gpt-5.5",
        "label": "OpenAI / GPT-5.5",
        "provider_id": "openai",
        "upstream_model": "gpt-5.5",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-5.4",
        "label": "OpenAI / GPT-5.4",
        "provider_id": "openai",
        "upstream_model": "gpt-5.4",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-5.4-mini",
        "label": "OpenAI / GPT-5.4-mini",
        "provider_id": "openai",
        "upstream_model": "gpt-5.4-mini",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-4o",
        "label": "OpenAI / GPT-4o",
        "provider_id": "openai",
        "upstream_model": "gpt-4o",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-4o-mini",
        "label": "OpenAI / GPT-4o-mini",
        "provider_id": "openai",
        "upstream_model": "gpt-4o-mini",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-4-turbo",
        "label": "OpenAI / GPT-4 Turbo",
        "provider_id": "openai",
        "upstream_model": "gpt-4-turbo",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-4.1",
        "label": "OpenAI / GPT-4.1",
        "provider_id": "openai",
        "upstream_model": "gpt-4.1",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/gpt-4.1-mini",
        "label": "OpenAI / GPT-4.1-mini",
        "provider_id": "openai",
        "upstream_model": "gpt-4.1-mini",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAI_CHAT_TASKS),
        "builtin": True,
    },
    {
        "id": "openai/text-embedding-3-large",
        "label": "OpenAI / text-embedding-3-large",
        "provider_id": "openai",
        "upstream_model": "text-embedding-3-large",
        "model_kind": "embedding",
        "supports_vision": False,
        "supported_tasks": ["embedding"],
        "builtin": True,
    },
    {
        "id": "openai/text-embedding-3-small",
        "label": "OpenAI / text-embedding-3-small",
        "provider_id": "openai",
        "upstream_model": "text-embedding-3-small",
        "model_kind": "embedding",
        "supports_vision": False,
        "supported_tasks": ["embedding"],
        "builtin": True,
    },
    {
        "id": "codex-cli/gpt-5.4-mini",
        "label": "Codex CLI / GPT-5.4-mini",
        "provider_id": "codex-cli",
        "upstream_model": "gpt-5.4-mini",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_CODEX_ALL_NON_EMBED_TASKS),
        "builtin": True,
    },
    {
        "id": "codex-cli/gpt-5.4",
        "label": "Codex CLI / GPT-5.4",
        "provider_id": "codex-cli",
        "upstream_model": "gpt-5.4",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_CODEX_ALL_NON_EMBED_TASKS),
        "builtin": True,
    },
    {
        "id": "codex-cli/gpt-5.5",
        "label": "Codex CLI / GPT-5.5",
        "provider_id": "codex-cli",
        "upstream_model": "gpt-5.5",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_CODEX_ALL_NON_EMBED_TASKS),
        "builtin": True,
    },
    {
        "id": "kimi/kimi-k2.5",
        "label": "Kimi / kimi-k2.5",
        "provider_id": "kimi",
        "upstream_model": "kimi-k2.5",
        "model_kind": "chat",
        "supports_vision": True,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "kimi/moonshot-v1-8k",
        "label": "Kimi / moonshot-v1-8k",
        "provider_id": "kimi",
        "upstream_model": "moonshot-v1-8k",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "deepseek/deepseek-v4-flash",
        "label": "DeepSeek / deepseek-v4-flash",
        "provider_id": "deepseek",
        "upstream_model": "deepseek-v4-flash",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "deepseek/deepseek-v4-pro",
        "label": "DeepSeek / deepseek-v4-pro",
        "provider_id": "deepseek",
        "upstream_model": "deepseek-v4-pro",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "qwen/qwen-flash",
        "label": "Qwen / qwen-flash",
        "provider_id": "qwen",
        "upstream_model": "qwen-flash",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "qwen/qwen-plus",
        "label": "Qwen / qwen-plus",
        "provider_id": "qwen",
        "upstream_model": "qwen-plus",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "qwen/qwen-max",
        "label": "Qwen / qwen-max",
        "provider_id": "qwen",
        "upstream_model": "qwen-max",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "minimax/MiniMax-M2.7-highspeed",
        "label": "MiniMax / MiniMax-M2.7-highspeed",
        "provider_id": "minimax",
        "upstream_model": "MiniMax-M2.7-highspeed",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
    {
        "id": "minimax/MiniMax-M2.7",
        "label": "MiniMax / MiniMax-M2.7",
        "provider_id": "minimax",
        "upstream_model": "MiniMax-M2.7",
        "model_kind": "chat",
        "supports_vision": False,
        "supported_tasks": deepcopy(_OPENAPI_LLM_TASKS),
        "builtin": True,
    },
]
